src/objects/Preference__c.object
<CustomObject>
    <description>Records Account or Contact Preferences, including Preference information or other details such as: Interests, Appeals, Benefits, Communications, Volunteers, Ratings, Education, Board/Trustee.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account related to the Preference being entered.</description>
        <inlineHelpText>Account related to the Preference being entered.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Preferences</relationshipLabel>
        <relationshipName>Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is this preference still active and valid?</description>
        <inlineHelpText>Is this preference still active and valid?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Indicates the highest level differentiator of a Preference (Interests, Appeals, Benefits, Communications, Etc). Controlling Field for Subcategory.</description>
        <inlineHelpText>Indicates the highest level differentiator of a Preference (Interests, Appeals, Benefits, Communications, Etc). Controlling Field for Subcategory.</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Code_Value__c</fullName>
        <description>Automatically populated value which signifies the pick list values contained within the Category, Subcategory, Type and Subtype fields.</description>
        <inlineHelpText>Automatically populated value which signifies the pick list values contained within the Category, Subcategory, Type and Subtype fields.</inlineHelpText>
        <label>Code Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact related to the Preference record.</description>
        <inlineHelpText>Contact related to the Preference record.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Preferences</relationshipLabel>
        <relationshipName>Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Indicates the date this preference ends and ceases to be valid.</description>
        <inlineHelpText>Indicates the date this preference ends and ceases to be valid.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Indicates the date this preference begins.</description>
        <inlineHelpText>Indicates the date this preference begins.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <description>Indicates the second highest level differentiator of a Preference. Controlled by the Category field, this is the controlling field for the Type field.</description>
        <inlineHelpText>Indicates the second highest level differentiator of a Preference. Controlled by the Category field, this is the controlling field for the Type field.</inlineHelpText>
        <label>Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <description>Indicates the fourth and lowest level differentiator of a Preference, controlled by the Category, Subcategory and Type fields.</description>
        <inlineHelpText>Indicates the fourth and lowest level differentiator of a Preference, controlled by the Category, Subcategory and Type fields.</inlineHelpText>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>II</fullName>
                </value>
                <value>
                    <fullName>III</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Indicates the third highest level differentiator of a Preference. Controlled by the Category and Subcategory fields, this is the controlling field for the Subtype field.</description>
        <inlineHelpText>Indicates the third highest level differentiator of a Preference. Controlled by the Category and Subcategory fields, this is the controlling field for the Subtype field.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Subcategory__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>a</fullName>
                </value>
                <value>
                    <fullName>b</fullName>
                </value>
                <value>
                    <fullName>c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Preference</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Preference_Code__c.object
<CustomObject>
    <description>Reference table that allows integrated objects or packages to access the full Preferences object picklist dependency structure.</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Indicates the highest level differentiator of a Preference.</description>
        <label>Category</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Value__c</fullName>
        <description>Code Value which signifies the pick list values contained within the Category, Subcategory, Type and Subtype fields.</description>
        <externalId>true</externalId>
        <inlineHelpText>Code Value which signifies the pick list values contained within the Category, Subcategory, Type and Subtype fields.</inlineHelpText>
        <label>Code Value</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <description>Indicates the second highest level differentiator of a Preference.</description>
        <inlineHelpText>Indicates the second highest level differentiator of a Preference.</inlineHelpText>
        <label>Subcategory</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <description>Indicates the fourth and lowest level differentiator of a Preference.</description>
        <inlineHelpText>Indicates the fourth and lowest level differentiator of a Preference.</inlineHelpText>
        <label>Subtype</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Indicates the third highest level differentiator of a Preference.</description>
        <inlineHelpText>Indicates the third highest level differentiator of a Preference.</inlineHelpText>
        <label>Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Preference Code</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preference Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Preference_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for controlling Preference automations.</description>
    <label>Preference Settings</label>
</CustomObject>

src/classes/Preference_TDTM_TEST.cls
@isTest
private class Preference_TDTM_TEST {

	@testSetup static void setup() {
		// Retrieve default NPSP Trigger Handlers
		List<npsp__Trigger_Handler__c> triggerHandlers = npsp.TDTM_Config_API.getCachedRecords();
		// Add our Trigger Handler to cached Trigger Handlers
		npsp__Trigger_Handler__c th = new npsp__Trigger_Handler__c();
		th.Name = 'Preference__c';
		th.npsp__Class__c = 'Preference_TDTM';
		th.npsp__Object__c = 'Preference__c';
		th.npsp__Trigger_Action__c = 'BeforeInsert;BeforeUpdate';
		th.npsp__Active__c = true;
		th.npsp__Load_Order__c = 1;
		th.npsp__Asynchronous__c = false;
		triggerHandlers.add(th);
		upsert triggerHandlers;
		// Create default Preference Settings record
		Preference_Settings__c settings = Preference_Settings__c.getInstance();
		upsert settings;
	}

	@isTest static void testAutoPopulate() {
		// Insert Preference Code
		Preference_Code__c pc = createPreferenceCode('Test', '1', 'A', 'a', 'I');
		insert pc;
		Test.startTest();
		// Create Preference with same Code Value
		Preference__c p = createPreference(pc.Code_Value__c, null, null, null, null);
		insert p;
		Test.stopTest();
		// Verify that Preference has all values from Preference Code
		p = [SELECT Category__c, Subcategory__c, Type__c, Subtype__c FROM Preference__c WHERE Id = :p.Id];
		for (String f : new List<String>{'Category__c', 'Subcategory__c', 'Type__c', 'Subtype__c'}) {
			System.assertEquals(pc.get(f), p.get(f));
		}
	}

	@isTest static void testCreatePreferenceCode() {
		Test.startTest();
		// Insert Preference with no Code Value but associated values to Preference Code
		Preference__c p = createPreference('Test', '1', 'A', 'a', 'I');
		insert p;
		Test.stopTest();
		// Verify Preference Code was created
		Preference_Code__c pc = [SELECT Category__c, Subcategory__c, Type__c, Subtype__c FROM Preference_Code__c WHERE Code_Value__c = :p.Code_Value__c];
		for (String f : new List<String>{'Category__c', 'Subcategory__c', 'Type__c', 'Subtype__c'}) {
			System.assertEquals(p.get(f), pc.get(f));
		}
	}

	@isTest static void testDefaultStartDate() {
		Test.startTest();
		// Insert Preference with no Code Value but associated values to Preference Code
		Preference__c p = createPreference(null, '1', 'A', 'a', 'I');
		insert p;
		Test.stopTest();
		// Verify Start Date was set to today
		p = [SELECT Start_Date__c FROM Preference__c WHERE Id = :p.Id];
		System.assertEquals(Date.today(), p.Start_Date__c);
	}

	@isTest static void testSyncActiveEndDate() {
		Test.startTest();
		// Insert Preferences with Active false and End Date not null
		Preference__c p1 = createPreference(null, '1', 'A', 'a', 'I');
		p1.Active__c = false;
		Preference__c p2 = createPreference(null, '2', 'B', 'b', 'II');
		p2.End_Date__c = Date.today();
		insert new List<Preference__c>{p1,p2};
		// Verify End Date was set to today
		p1 = [SELECT End_Date__c FROM Preference__c WHERE Id = :p1.Id];
		System.assertEquals(Date.today(), p1.End_Date__c);
		// Verify Active was set to false
		p2 = [SELECT Active__c FROM Preference__c WHERE Id = :p2.Id];
		System.assertEquals(false, p2.Active__c);
		// Update Preferences to Active true and End Date null
		p1.Active__c = true;
		p2.End_Date__c = null;
		update new List<Preference__c>{p1,p2};
		// Verify End Date cleared
		p1 = [SELECT End_Date__c FROM Preference__c WHERE Id = :p1.Id];
		System.assertEquals(null, p1.End_Date__c);
		// Verify Active was set to true
		p2 = [SELECT Active__c FROM Preference__c WHERE Id = :p2.Id];
		System.assertEquals(true, p2.Active__c);
		Test.stopTest();
	}

	@isTest static void testUpdateAccount() {
		// Create Account and Contact
		Account a = new Account(Name = 'Test');
		insert a;
		Contact c = new Contact(AccountId = a.Id, LastName = 'Test');
		insert c;
		Test.startTest();
		// Insert Preference with only Contact set
		Preference__c p = createPreference(null, '1', 'A', 'a', 'I');
		p.Contact__c = c.Id;
		insert p;
		Test.stopTest();
		// Verify Account set
		p = [SELECT Account__c FROM Preference__c WHERE Id = :p.Id];
		System.assertEquals(a.Id, p.Account__c);
	}

	@isTest static void testUpdateCodeValue() {
		// Insert Preference Code
		Preference_Code__c pc = createPreferenceCode('Test', '1', 'A', 'a', 'I');
		insert pc;
		Test.startTest();
		// Insert Preference with no Code Value but associated values to Preference Code
		Preference__c p = createPreference(null, '1', 'A', 'a', 'I');
		insert p;
		Test.stopTest();
		// Verify Code Value was set on Preference
		p = [SELECT Code_Value__c FROM Preference__c WHERE Id = :p.Id];
		System.assertEquals(pc.Code_Value__c, p.Code_Value__c);
	}

	// Create Preference and Preference Code with specified parameters
	private static Preference__c createPreference(String codeValue, String category, String subcategory, String type, String subtype) {
		return new Preference__c(Code_Value__c = codeValue, Category__c = category, Subcategory__c = subcategory, Type__c = type, Subtype__c = subtype);
	}
	private static Preference_Code__c createPreferenceCode(String codeValue, String category, String subcategory, String type, String subtype) {
		return new Preference_Code__c(Code_Value__c = codeValue, Category__c = category, Subcategory__c = subcategory, Type__c = type, Subtype__c = subtype);
	}
}