src/objects/Preference__c.object
<CustomObject>
    <description>Records Account or Contact Preferences, including Preference information or other details such as: Interests, Appeals, Benefits, Communications, Volunteers, Ratings, Education, Board/Trustee.</description>
    <fields>
        <fullName>Account_ID__c</fullName>
        <description>18-digit Account ID to be used in Matching Rules.</description>
        <inlineHelpText>18-digit Account ID to be used in Matching Rules.</inlineHelpText>
        <label>Account ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account related to the Preference being entered.</description>
        <inlineHelpText>Account related to the Preference being entered.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Preferences</relationshipLabel>
        <relationshipName>Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is this preference still active and valid?</description>
        <inlineHelpText>Is this preference still active and valid?</inlineHelpText>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>Indicates the highest level differentiator of a Preference (Interests, Appeals, Benefits, Communications, Etc). Controlling Field for Subcategory.</description>
        <inlineHelpText>Indicates the highest level differentiator of a Preference (Interests, Appeals, Benefits, Communications, Etc). Controlling Field for Subcategory.</inlineHelpText>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Code_Value__c</fullName>
        <description>Automatically populated value which signifies the pick list values contained within the Category, Subcategory, Type and Subtype fields.</description>
        <inlineHelpText>Automatically populated value which signifies the pick list values contained within the Category, Subcategory, Type and Subtype fields.</inlineHelpText>
        <label>Code Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_ID__c</fullName>
        <description>18-digit Contact ID to be used in Matching Rules.</description>
        <inlineHelpText>18-digit Contact ID to be used in Matching Rules.</inlineHelpText>
        <label>Contact ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact related to the Preference record.</description>
        <inlineHelpText>Contact related to the Preference record.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Preferences</relationshipLabel>
        <relationshipName>Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <description>Indicates the date this preference ends and ceases to be valid.</description>
        <inlineHelpText>Indicates the date this preference ends and ceases to be valid.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Indicates the date this preference begins.</description>
        <inlineHelpText>Indicates the date this preference begins.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <description>Indicates the second highest level differentiator of a Preference. Controlled by the Category field, this is the controlling field for the Type field.</description>
        <inlineHelpText>Indicates the second highest level differentiator of a Preference. Controlled by the Category field, this is the controlling field for the Type field.</inlineHelpText>
        <label>Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <description>Indicates the fourth and lowest level differentiator of a Preference, controlled by the Category, Subcategory and Type fields.</description>
        <inlineHelpText>Indicates the fourth and lowest level differentiator of a Preference, controlled by the Category, Subcategory and Type fields.</inlineHelpText>
        <label>Subtype</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>I</fullName>
                </value>
                <value>
                    <fullName>II</fullName>
                </value>
                <value>
                    <fullName>III</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Indicates the third highest level differentiator of a Preference. Controlled by the Category and Subcategory fields, this is the controlling field for the Subtype field.</description>
        <inlineHelpText>Indicates the third highest level differentiator of a Preference. Controlled by the Category and Subcategory fields, this is the controlling field for the Subtype field.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Subcategory__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>a</fullName>
                </value>
                <value>
                    <fullName>b</fullName>
                </value>
                <value>
                    <fullName>c</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Preference</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Preference_Code__c.object
<CustomObject>
    <description>Reference table that allows integrated objects or packages to access the full Preferences object picklist dependency structure.</description>
    <fields>
        <fullName>Category__c</fullName>
        <description>Indicates the highest level differentiator of a Preference.</description>
        <label>Category</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code_Value__c</fullName>
        <description>Code Value which signifies the pick list values contained within the Category, Subcategory, Type and Subtype fields.</description>
        <externalId>true</externalId>
        <inlineHelpText>Code Value which signifies the pick list values contained within the Category, Subcategory, Type and Subtype fields.</inlineHelpText>
        <label>Code Value</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <description>Indicates the second highest level differentiator of a Preference.</description>
        <inlineHelpText>Indicates the second highest level differentiator of a Preference.</inlineHelpText>
        <label>Subcategory</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subtype__c</fullName>
        <description>Indicates the fourth and lowest level differentiator of a Preference.</description>
        <inlineHelpText>Indicates the fourth and lowest level differentiator of a Preference.</inlineHelpText>
        <label>Subtype</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Indicates the third highest level differentiator of a Preference.</description>
        <inlineHelpText>Indicates the third highest level differentiator of a Preference.</inlineHelpText>
        <label>Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Preference Code</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Reference #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Preference Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Preference_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings for controlling Preference automations.</description>
    <fields>
        <fullName>Auto_Populate_Fields__c</fullName>
        <description>In addition to Category, Subcategory, Type, and Subtype, comma-separated list of other fields that will copy from Preference Code to Preference based on the defined Preference Code.</description>
        <inlineHelpText>In addition to Category, Subcategory, Type, and Subtype, comma-separated list of other fields that will copy from Preference Code to Preference based on the defined Preference Code.</inlineHelpText>
        <label>Auto Populate Fields</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Disable_Auto_Populate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, Preference records will not populate based on a defined Preference Code.</description>
        <inlineHelpText>When checked, Preference records will not populate based on a defined Preference Code.</inlineHelpText>
        <label>Disable Auto Populate?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Create_Preference_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, Preference Code records will not be created by data entered on Preference record. Otherwise, Preference Codes created with specified Code Value, Category, Subcategory, Type, and Subtype.</description>
        <inlineHelpText>When checked, Preference Code records will not be created by data entered on Preference record. Otherwise, Preference Codes created with specified Code Value, Category, Subcategory, Type, and Subtype.</inlineHelpText>
        <label>Disable Create Preference Code?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Default_Start_Date__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, disables setting Start Date to today if not filled out on insert.</description>
        <inlineHelpText>When checked, disables setting Start Date to today if not filled out on insert.</inlineHelpText>
        <label>Disable Default Start Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Sync_Active_End_Date__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, disables syncing the Active value with the presence of an End Date.</description>
        <inlineHelpText>When checked, disables syncing the Active value with the presence of an End Date.</inlineHelpText>
        <label>Disable Sync Active / End Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Update_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, disables Account from being automatically set when Contact is set but Account is not.</description>
        <inlineHelpText>When checked, disables Account from being automatically set when Contact is set but Account is not.</inlineHelpText>
        <label>Disable Update Account?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Disable_Update_Code_Value__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checked, Code Value from the associated Preference Code will not be populated on Preference when Code Value is blank.</description>
        <inlineHelpText>When checked, Code Value from the associated Preference Code will not be populated on Preference when Code Value is blank.</inlineHelpText>
        <label>Disable Update Code Value?</label>
        <type>Checkbox</type>
    </fields>
    <label>Preference Settings</label>
</CustomObject>

src/classes/Preference_TDTM.cls
global class Preference_TDTM extends npsp.TDTM_RunnableMutable {

    global override void run(List<SObject> newlist, List<SObject> oldlist, npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult, npsp.TDTM_Runnable.DmlWrapper dmlWrapper) {
        // Cast new and old list to Preference list
        List<Preference__c> newRecords = (List<Preference__c>) newlist;
        List<Preference__c> oldRecords = (List<Preference__c>) oldlist;
		// Run on before insert and update
        if (triggerAction == npsp.TDTM_Runnable.Action.BeforeInsert) {
        	onBeforeInsertUpdate(newRecords, null, dmlWrapper);
        }                                     
        else if (triggerAction == npsp.TDTM_Runnable.Action.BeforeUpdate) {
          	onBeforeInsertUpdate(newRecords, oldRecords, dmlWrapper);
        }
    }
    
    // Get Preference Settings for current User
    static Preference_Settings__c settings = Preference_Settings__c.getInstance();
    
    // Common method to set fields on before insert and before update
    private static void onBeforeInsertUpdate(List<Preference__c> newList, List<Preference__c> oldList, npsp.TDTM_Runnable.DmlWrapper dmlWrapper) {
        // Construct oldMap
        Map<Id,Preference__c> oldMap = new Map<Id,Preference__c>();
        if (oldList != null) {
            for (Preference__c p : oldList) {
                oldMap.put(p.Id, p);
            }
        }
        // Instantiate collections
        Set<String> codes = new Set<String>();
        Map<String,Preference_Code__c> codeMap = new Map<String,Preference_Code__c>();
        Set<String> categories = new Set<String>();
        Set<String> subcategories = new Set<String>();
        Set<String> types = new Set<String>();
        Set<String> subtypes = new Set<String>();
        Map<Id,Contact> conMap = new Map<Id,Contact>();
        List<Preference_Code__c> prefCodes = new List<Preference_Code__c>();
        // Set default Preference Code fields to populate and any user-defined fields
        List<String> pcFields = new List<String>{'Category__c','Subcategory__c','Type__c','Subtype__c'};
        pcFields.addAll(!String.isBlank(settings.Auto_Populate_Fields__c) ? settings.Auto_Populate_Fields__c.deleteWhitespace().split(',') : new List<String>());
        // Loop through Preferences to get initial collections
        for (Preference__c p : newList) {
            if (!settings.Disable_Auto_Populate__c) {
                // If Code Value not blank, add to set
            	if (oldList == null && !String.isBlank(p.Code_Value__c)) {
            		codes.add(p.Code_Value__c);
                }
            }
            // If should update Code Value on insert
            if (!settings.Disable_Update_Code_Value__c) {
                // If Code Value not specified, collect field values
                if (oldList == null && String.isBlank(p.Code_Value__c)) {
                    if (!String.isBlank(p.Category__c)) {
                        categories.add(p.Category__c);
                    }
                    if (!String.isBlank(p.Subcategory__c)) {
                        subcategories.add(p.Subcategory__c);
                    }
                    if (!String.isBlank(p.Type__c)) {
                        types.add(p.Type__c);
                    }
                    if (!String.isBlank(p.Subtype__c)) {
                        subtypes.add(p.Subtype__c);
                    }
                }
            }
            if (!settings.Disable_Create_Preference_Code__c) {
                // If Code Value set, add to set
                if (oldList == null && !String.isBlank(p.Code_Value__c)) {
                    codes.add(p.Code_Value__c);
                }
            }
            if (!settings.Disable_Update_Account__c) {
                // If Contact set but Account is not, add to Contact Map
            	if (p.Contact__c != null && p.Account__c == null) {
            		conMap.put(p.Contact__c, null);
                }
            }
        }
        // If either codes or categories filled out, then means some automation should run for Preference Codes
        if (!codes.isEmpty() || !categories.isEmpty()) {
            // Query all the fields on Preference Code for relevant Preference Codes
            String query = 'SELECT ' + String.join(new List<String>(SObjectType.Preference_Code__c.fields.getMap().keySet()), ', ') + ' FROM Preference_Code__c WHERE Code_Value__c IN :codes OR (Category__c in :categories AND Subcategory__c IN :subcategories AND Type__c IN :types AND Subtype__c IN :subtypes)';
            for (Preference_Code__c pc : (List<Preference_Code__c>)Database.query(query)) {
                // Add Preference Code to codeMap for both Code Value and field combination
                codeMap.put(pc.Code_Value__c, pc);
                codeMap.put(getKey(pc), pc);
            }
        }
        // Get map of Contacts set
        conMap = new Map<Id,Contact>([SELECT Id, AccountId FROM Contact WHERE Id IN :conMap.keySet()]);
        // Loop through Preferences again
        for (Preference__c p : newList) {
            // Get old Preference if exists
            Preference__c oldP = oldList == null ? null : oldMap.get(p.Id);
            if (!settings.Disable_Update_Account__c) {
                // If Contact set but Account is not
            	if (p.Contact__c != null && p.Account__c == null) {
                    // Update Account to Contact's Account
                    p.Account__c = conMap.get(p.Contact__c).AccountId;
                }
            }
            // Set text fields for Account and Contact
            p.Account_ID__c = p.Account__c;
            p.Contact_ID__c = p.Contact__c;
            // If specified Code Value exists
            if (!settings.Disable_Auto_Populate__c && oldList == null && !String.isBlank(p.Code_Value__c) && codeMap.containsKey(p.Code_Value__c)) {
                // Apply all the Preference Code values to the Preference
                Preference_Code__c pc = codeMap.get(p.Code_Value__c);
                for (String pcField : pcFields) {
                    p.put(pcField, pc.get(pcField));
                }
            }
            // Otherwise if Code Value set and doesn't already exist in Preference Code
            else if (!settings.Disable_Create_Preference_Code__c && oldList == null && !String.isBlank(p.Code_Value__c) && !codeMap.containsKey(p.Code_Value__c)) {
                // Create new Preference Code
                prefCodes.add(new Preference_Code__c(
                    Code_Value__c = p.Code_Value__c,
                    Category__c = p.Category__c,
                    Subcategory__c = p.Subcategory__c,
                    Type__c = p.Type__c,
                    Subtype__c = p.Subtype__c
                ));
            }
            // If should Update Code Value
            else if (!settings.Disable_Update_Code_Value__c) {
                // If Code Value not set but field combinations matches existing Code Value
                if (oldList == null && String.isBlank(p.Code_Value__c) && codeMap.containsKey(getKey(p))) {
                    // Set Code Value according to Preference Code
                    p.Code_Value__c = codeMap.get(getKey(p)).Code_Value__c;
                }
            }
            // If Start Date not set on insert
            if (!settings.Disable_Default_Start_Date__c) {
                if (p.Start_Date__c == null && oldList == null) {
                    // Set Start Date as today
                    p.Start_Date__c = Date.today();
                }
            }
            // If should sync Active and End Date fields
            if (!settings.Disable_Sync_Active_End_Date__c) {
                // If just set Active False but End Date is null
                if (!p.Active__c && p.End_Date__c == null && (oldList == null || oldP.Active__c)) {
                    // Set End Date to today
                    p.End_Date__c = Date.today();
                }
                // If just set End Date but Active
                else if (p.Active__c && p.End_Date__c != null && (oldList == null || p.End_Date__c != oldP.End_Date__c)) {
                    // Set Active to false
                    p.Active__c = false;
                }
                // If Active just set to true but End Date filled out
                else if (p.Active__c && p.End_Date__c != null && oldList != null && !oldP.Active__c) {
                    // Clear End Date
                    p.End_Date__c = null;
                }
                // If End Date just cleared but Active false
                else if (!p.Active__c && p.End_Date__c == null && oldList != null && p.End_Date__c != oldP.End_Date__c) {
                    // Set Active to true
                    p.Active__c = true;
                }
            }
        }
        // Insert new Preference Codes
        dmlWrapper.objectsToInsert.addAll(prefCodes);
    }
    
    // Get unique key for Preferences and Preference Codes
    private static String getKey(sObject s) {
        return elide(s.get('Category__c')) + ';' + elide(s.get('Subcategory__c')) + ';' + elide(s.get('Type__c')) + ';' + elide(s.get('Subtype__c'));
    }
    
    // Return empty string if string null or blank
    private static String elide(Object s) {
        return String.isBlank(String.valueOf(s)) ? '' : String.valueOf(s);
    }
}